language: c++

os:
  - linux

language: cpp

dist: trusty

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - g++-7

install:
  - export CC=gcc-7
  - export CXX="g++-7 -std=c++14"

script:
  - cmake -H. -Bbuild
  - cd build
  - cmake --build .
  - cd test
  - ctest

