language: c++

os:
  - linux

language: cpp

dist: trusty

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - g++-7

before_install:
  - pip install --user cpp-coveralls

install:
  - export CC=gcc-7
  - export CXX="g++-7 -std=c++14"

script:
  - cmake -H. -Bbuild -DENABLE_COVERAGE=ON
  - cd build
  - cmake --build .
  - cd test
  - ctest

after_success:
  - coveralls --gcov gcov-7 --gcov-options '\-lp' --root ${TRAVIS_BUILD_DIR} --build-root ${TRAVIS_BUILD_DIR}/build --include gpio --include motor_control --exclude raspberrypi --exclude test

notifications:
  email: false
