language: c++

os:
  - linux

language: cpp

dist: trusty

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - g++-7
      - gcov-7

before_install:
  - pip install --user cpp-coveralls

install:
  - export CC=gcc-7
  - export CXX="g++-7 -std=c++14"
  - export GCOV=gcov-7

script:
  - cmake -H. -Bbuild -DENABLE_COVERAGE=ON
  - cd build
  - cmake --build .
  - cd test
  - ctest

after_success:
  - coveralls --root . -E ".*googletest.*" -E ".*CMakeFiles.*" -E ".*test/.*.cpp.*"

notifications:
  email: false
